[project]
name = "engine"
version = "1.0.0"
description = ""
readme = "README.md"
authors = [
    {name = "Wei-Cheng Pan", email = "legnaleurc@gmail.com"}
]
dynamic = ["dependencies", "requires-python"]

[tool.poetry]
requires-poetry = "^2.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
aiohttp = "^3.13.2"
wcpan-drive-core = "^4.1.0"
wcpan-drive-crypt = "^4.1.2"
wcpan-drive-google = "^9.1.7"
wcpan-watchdog = "^1.0.0"
wcpan-drive-cli = "^3.8.1"
wcpan-logging = "^2.1.0"
wcpan-drive-sqlite = "^2.0.0"
pillow = "^12.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
